### ISSUE TITLE
[Feat] 보호자 연결 기능 작성

### ISSUE THREAD

**Issue by woog2roid** [Blood-Mate/blood-mate-app#10]
전화번호를 이용해서 보호자를 연결하고, 이를 보여주는 페이지를 만들어야 할 듯 합니다

나를보호자로등록/ 내가보호자로등록 / 그 외의 순서로 보여준다고 했던 듯 합니다.

이 부분의 구체적인 기획은 comment로 남겨주세요

**Comment by ko-success** [comment]
acquaintance page 에서 
1. 나를 보호자로 등록 2. 내가 보호자로 등록 3. 앱 가입된 친구 4. 앱 미가입 친구
순으로 보여줄겁니다. 
각각의 tile이 조금씩 다를거고, 1 과 2, 3은 서로다른 팝업을 가집니다.
- 팝업에는 더 자세한 프로필 정보 + 각각 보호자 글쓰기 / 보호자로 등록의 기능이 들어갈 예정인데 일단 똑같은 프로필 데이터 조회에 기능만 추가해서 만들 예정입니다.

나를 보호자로 등록한 사람 view와 그 외 친구 view 두개로 나누어 작성할것같습니다.

**Comment by woog2roid** [comment]
주로 건드리는 파일은
- view/acquaintance
- viewmodel/acquaintance
- repository/acquaintance
- 필요한 model들
이렇게 되는게 맞나요?
=> 이걸 알아야 저희 협업 구조 상, conflict를 줄일 수 있어보여요.
=> repository를 만들고 view를 짜는 방식.

저희 swagger에서 어떤 api를 쓰게 되나요?\
=> 말씀 주시면 만들게요.
