### ISSUE TITLE
[Refactor] 아키텍처 정리

### ISSUE THREAD

**Issue by woog2roid** [Blood-Mate/blood-mate-app#11]
https://github.com/Blood-Mate/blood-mate-app/issues/6 가 끝난 후,
conflict가 나지 않도록 refactoring을 하려고 합니다.

datasource 분리 이 외로 필요한 거 있을까요?
- page view 합치기 등

다만, 시간이 없으니 필요한 리팩토링만 했으면 합니다.
적당한 기술부채는 가지고 가야할 듯 하네요.

**Comment by ko-success** [comment]
네 일단 후딱하져

**Comment by ko-success** [comment]
아 datasource관련해서 얘기하고 싶은 게 있는데, 아예 get/post/delete/patch에 대한 규격을 remote data source에다 넣고 repository에서 더 자세하게 쓰는 방법이 있던데 이거에 대해선 어떻게 생각하나요?

**Comment by woog2roid** [comment]
> 아 datasource관련해서 얘기하고 싶은 게 있는데, 아예 get/post/delete/patch에 대한 규격을 remote data source에다 넣고 repository에서 더 자세하게 쓰는 방법이 있던데 이거에 대해선 어떻게 생각하나요?

회의 후에, dio를 uitlize하지는 않고, data source layer를 삭제하는 것으로 하기로 하였습니다.

**Comment by woog2roid** [comment]
**진행하기로 결정난 사항**
1. MVVM에 repository만 넣는 것으로 하였음.
  - 추가적인 회의로, 담당 파트를 정하는 것이 좋아보입니다.
2. page-view는 합치는 것으로 얘기가 나왔음.


**@ko-success 판단 하 진행할 사항**
폴더링 정리 (아래와 같은 폴더링이 깔끔할 수 있으나, 본인 판단 하 진행하세요.)
1. dio_factory를 ./lib쪽으로 밖으로 빼기
   - 결국 단순한 dio utility에 지나지 않습니다.
2. ui폴더를 삭제하고, view, viewmodel만 남기기
   - view내부에 페이지별로 폴더링 후, 실제 여러 위젯들을 합친 페이지 파일에는 page라고만 적어주기
   - common은 view/common으로 들어가기
   - 아래와 같은 모습일 수 있겠네요
      - view/common, view/main, view/friend ....
      - view/main/post.dart, view/main/profile.dart view/main/page.dart
      - view/common/top_nav.dart view/common/bottom_nav.dart view/common/button.dart 등
 3. data에 있는 것도 밖으로 뺄 수 있는 것이 좋아보입니다.
    - lib/data/repository? lib/repository? 굳이...?

**Comment by ko-success** [comment]
view파일명 관련해서 논의사항입니다.
homepage 폴더 내 profile.dart와 profilepage 폴더 내 profile.dart는 이름을 다르게 할건가요? 두 파일이 아예 다른 view긴 합니다.
