### ISSUE TITLE
Feat(main): 뷰모델, 레포지토리 제작

### ISSUE THREAD

**Issue by woog2roid** [Blood-Mate/blood-mate-app#16]
# 메인페이지의 뷰모델, 메인페이지를 제작하는 업무

## 해야하는 업무
- 자신이 읽어야 할 포스트들을 불러오는 API제작

## 수정(추가)할 파일 및 폴더링
- /lib/data/repository/post_repository.dart
- /lib/viewmodel/home_viewmodel.dart

## 요청사항
viewmodel은 페이지 이름과 통일해주세요.
- mainpage의 viewmodel은 main_viewmodel
- signinpage의 viewmodel은 signin_viewmodel
- ...etc...

**Comment by woog2roid** [comment]
더 필요한 사항은 comment로 올려주세요

**Comment by ko-success** [comment]
1. 친구 헌혈 페이지
- 메인 페이지의 더보기 버튼을 누를 시 페이지가 띄워지고 좀 더 큰 list tile로 이루어진 list 생성
2. 친구 헌혈 글
- 메인 페이지에서 친구 news list나 친구 헌혈 페이지에서 tile 클릭 시 해당 글 페이지로 넘어감

**Comment by ko-success** [comment]
보면 private post/ public post 두개가 있는데 둘 다 범용적으로 쓸 수 있는 post model 제작해주세요
형식은 다른 모델과 똑같이 작성 후 flutter pub run build_runner build 해주면 됩니다. 
이후 post repository에서 api들 만들어주시면 되고 포스트 페이지 뷰모델은 뷰 짜면서 계속 만져야하는거라(정확히 정리가 안돼서) 작업분리가 어려울 거 같아요. 모델이랑 레포까지만 만들어 주시면 될듯합니다.
