### ISSUE TITLE
[UI] UI part 제작

### ISSUE THREAD

**Issue by ko-success** [Blood-Mate/blood-mate-app#2]
- issue 1 branch에 commit하긴 했으나  design->model에서 model->design으로 순서를 바꿔서 진행중이므로 새로 issue를 작성함

- 전체를 data/ui로 나누어 진행
- ui는 page/view/viewmodel로 구성되어있다.
  -> viewmodel에서 data를 관리하고, view에서는 data를 view만함. page에서 한 화면 page를 구성하는 모든 view들을 viewmodel과 엮어줌
- data는 현재 data_source/model/repository로 구분
  -> data source에서는 local/remote 각각의 repo에서 data를 가져오는 api를 작성
       local은 hive 사용예정
  -> repository는 data source에서 불러온 data를 저장
  -> model은 API 명세에서 작성했던 model을 기반으로 작성, freezed로 제작

현재까지 main의 home_page 일부분 제작
앞으로 남은 4개의 page들과 login/signin 단계 완성요망
model 또한 local donation과 관련하여 추가 제작 필요
view->viewmodel로 넘어가는 gesture detection(수정/기입 등) 제작요망

DB에 연결이 되어있지 않아 mock data를 생성해서 제작중인데, 위에 기술한 app의 기본 기능은 제가 완성 할 수 있으나, 1. 로그인 관련 2. hive를 이용한 local storage 사용 // 의 두가지 기능은 다른 사람이 제작 부탁드립니다

**Comment by woog2roid** [comment]
위와 같은 구조로 로그인 관련 페이지를 만들면 되는 걸까요?

ps. 하나의 issue는 결국 하나의 pr과 대응하고, 하나의 pr은 하나의 기능 단위 commit (squash merge 기준)과 대응합니다. 다음 번에는 하나의 issue를 여러명이 작업하지 않도록, 기능단위로 issue를 잘게 자르면 더 좋을 것 같아요.
