### ISSUE TITLE
[Feat] Log in / Sign in

### ISSUE THREAD

**Issue by ko-success** [Blood-Mate/blood-mate-app#4]
start page : 로그인 / 회원가입 선택

sign in page : 1. email 인증 2. ID / PW 중복확인 3. 이름 및 전화번호,혈액형 4. complete 보여주고 log in page로 넘어가기 

log in page : page는 하나, option으로 forget PW

email 인증 / ID 중복확인 / 전화번호 중복확인 / login 해서 auth 받기 -> data 기능구현필요

**Comment by woog2roid** [comment]
1. 일단 제가 알기로는 ID는 없는거로 알고 있는데, ID 대신에 전화번호 넣는 거로 해볼게요(sign in page)
2. email 같은 경우에는 User 스키마에 아예 저장을 안했습니다

현재 전화번호/비밀번호로만 이루어져있는데 이에 맞춰서 제가 개발하면 될까요?

**Comment by ko-success** [comment]
1. 이게 고민인데 로그인 방식을 1) ID+PW 2) email+PW 3) PhoneNum+PW 세가지인데 2번이나 3번은 인증을 바탕으로 진행해야하고 1번은 후에 인증이 가능한 개념입니다. 
2. 앱을 가입하게 되면 전화번호로 문자를 보내는게 아닌 앱으로 글을 공유하기 때문에 가입시기에 전화번호가 크게 중요하지 않다고 생각합니다. 그래서 3번보단 1/2중에 택해서 하는게 좋아보여요. 스키마에 없다면...추가 가능할까요

**Comment by woog2roid** [comment]
어... 우선 전화번호로 했던 이유는
1. 핸드폰 연락처 기반으로 친구를 만들기 때문
2. unique해서 Id로 상당히 괜찮기 때문입니다.

지금 가상번호 관련해서 윤지님이 문제가 있으시던데, 제 생각으로는 phoneNumber 중복 확인 API를 열어줘서 회원가입시 확인시킨다. 말고는 딱히 좋은 방법이 떠오르지 않네요(당장 이 방법도 시간이 없고 데모니까 가능한 방법이긴 하지만요...)

Id를 만드는 게 인증이 불가능한 상황에서 좋아보이는데 이건 윤지님께 여쭤봐야 할 사항같습니다.

**Comment by woog2roid** [comment]
한다면, email보단 id가 깔끔할 듯 하긴 하네요...
email로 하면 괜히 또 이메일 인증 등의 여지를 줄 수 있거나 할 듯 한데
걍 id로 하면 훨씬 트집안잡히기... 좋아보이네요....

**Comment by yunz0926** [comment]
현재 백에서는 가입 시 phoneNumber, password, 기타 유저 정보(이름, 혈액형)을 받습니다.
이렇게 구현한 이유는 앞서 귀정님이 언급한 것처럼

**1. 번호를 기준으로 앱 내 연락처를 저장하고, 친구의 앱 등록 여부를 전화번호를 기준으로 찾는다.** 부연 설명을 하자면 현재까지 "앱 등록 친구는 앱으로 글을 공유하고, 앱 미등록 친구는 sms를 보낸다. 즉, 앱 가입 여부와 상관없이 친구를 저장할 수 있다" 의 기획이 있어서, 친구가 모두 앱에 등록되어있다는 보장을 못합니다. 따라서 두 종류의 친구를 모두 포함하기 위해서 친구 리스트에 친구의 아이디 값을 저장하지 못하고, 친구의 전화번호를 저장합니다. 그리고 해당 친구의 앱 가입 여부에 대한 판별도 친구의 전화번호로 등록 된 사용자의 유무를 체크하는 것입니다. 따라서 저희의 기획에서 전화번호는 매우 중요한 요소입니다.

**2. (1의 이유로) 사용자 별로 전화번호가 unique 하다 (해야한다)**
**3. (2의 이유로) 전화번호가 필수값이고 그에 따른 인증과정이 필요하다** _(sms 인증이 안된다고하면 중복 확인이라도)_


위와 같은 이유로 저는 가입 시기에 unique한 전화번호가 필수라고 생각해서 유저 아이디나 이메일 대신 전화번호를 채택했습니다.
이메일은 말한 것처럼 이메일 인증의 여지가 있어서 굳이 채택할 이유가 없다고 생각합니다. 그리고 유저 아이디는 만들어봤자 로그인 그 이상의 역할도 안하게 될 것이고,_(거의 대부분의 사용자 찾기 기능은 전화번호로 이루어지고, 보호자 등록 같은 앱 등록 사용자에 대한 기능은 유저 생성 시 디비 에서 자동 생성되는 id 값으로 할 수 있기 때문)_ phoneNumber가 unique한 상황에서 굳이 unique한 값을 두개를 만들어서 중복 확인 과정만 두번 거칠 필요가 없다고 생각해서입니다. 

필요하다면 id 값을 넣을 순 있으나, 프론트 쪽에서도 id 중복확인, 전화번호 중복 확인을 두번 하려면 오히려 번거롭지 않을까란 생각이 드네요
