### ISSUE TITLE
[Feat] 지인 지정 헌혈 게시물 최초작성

### ISSUE THREAD

**Issue by woog2roid** [Blood-Mate/blood-mate-app#8]
지정헌혈 게시물을 작성하는 feature 추가
- 보호자가 작성하는 경우
- 본인이 작성하는 경우
둘 다 포함됩니다.

게시물 작성 팝업페이지의 view는 그대로 쓰고,
"포스트 작성 완료" 버튼의 onPressed만 바꿔서 쓸 수 있다면 제일 좋을 것 같습니다.
- 아마 button은 본인작성과 보호자작성이 나뉘어질 것 같습니다.
- 파라미터가 달라요 ㅠ 이 부분은 swagger확인.
- 재활용이 되는 부분은 글 작성하는 부분 등이지 않을까 싶네요.

**Comment by woog2roid** [comment]
트위터를 따라하기로 했으니 리포스팅의 경우, 원글이 아래에 떠야된다는 점을 생각해서, 최초작성과 view가 달라질 수도 있을 듯합니다. 이 부분은 @ko-success 님이 생각해보신 후에 댓글 남겨주세요

**Comment by woog2roid** [comment]
또한, 통화로 회의한 내용대로, layer를 나누어서 작업하면 될 듯 합니다.

**Comment by ko-success** [comment]
1. 파라미터가 다르다는 말이 어떤걸 의미하는건가요?
2. 게시물 작성 view 자체는 본인 작성/보호자 작성 모두 동일합니다. API URL만 바꾸면 될것같아요.
 -> guardian get했을 때 response 모델을 보고싶은데 500 error가 뜨네요
3. repost는 기존 view에 원글 내용을 담은 card들을 넣는 식으로 새로 view를 짤 것 같아요

**Comment by woog2roid** [comment]
> 1. 파라미터가 다르다는 말이 어떤걸 의미하는건가요?
> 2. 게시물 작성 view 자체는 본인 작성/보호자 작성 모두 동일합니다. API URL만 바꾸면 될것같아요.
>    -> guardian get했을 때 response 모델을 보고싶은데 500 error가 뜨네요
> 3. repost는 기존 view에 원글 내용을 담은 card들을 넣는 식으로 새로 view를 짤 것 같아요

1. swagger API를 보면 보호자가 작성할 경우랑, 본인이 직접 작성할 경우랑 body에 넣어야 하는 데이터가 다릅니다.
2. 1번에서 말한대로, URL을 바꾸고 바디도 바꿔야 합니다. 500번 에러 해결했습니다.
3. 해당 파트는 따로 issue올리겠습니다.
